---
abstract: 'As ::Tiny as a module can get'
author:
  - 'Daniel Muey <http://drmuey.com/cpan_contact.pl>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Tiny
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
version: 0.5
